---
title: "3-shrinking to common columns"
output: html_notebook
---
Use this shrink if going to look at each country individually
```{r}
new_col <- unlist(all_common_col)

shrink <- function(country){
  country <- country[, new_col]
  return(country)
}

```


```{r}
library(purrr)
library(dplyr)

argentina_shrink  <- shrink(argentina)
belize_shrink  <- shrink(belize)
bolivia_shrink  <- shrink(bolivia)
brazil_shrink  <- shrink(brazil)
canada_shrink  <- shrink(canada)
chile_shrink  <- shrink(chile)
colombia_shrink  <- shrink(colombia)
costa_shrink <- shrink(costa)
ecuador_shrink <- shrink(ecuador)
elsalvador_shrink <- shrink(elsalvador)
guatemala_shrink <- shrink(guatemala)
#guyana_shrink <- shrink(guyana) Commented out because it is English-only
honduras_shrink <- shrink(honduras)
#jamaica_shrink <- shrink(jamaica) Commented out because it is English-only
mexico_shrink <- shrink(mexico)
nicaragua_shrink <- shrink(nicaragua)
panama_shrink <- shrink(panama)
paraguay_shrink <- shrink(paraguay)
peru_shrink <- shrink(peru)
suriname_shrink <- shrink(suriname)
usa_shrink <- shrink(usa)
uruguay_shrink <- shrink(uruguay)
venezuela_shrink <- shrink(venezuela)
```


Use this shrink if goin to do join on countries.... need to only allow in unique ones
```{r}
shrink2 <- function(country){
  y <- 1
  x <- 1
  new_col <- rep(NA, 128)
  columns <- attributes(country)$names
  while(x <= length(columns)){
    d <- (attributes(country[[columns[x]]]))$label
    if(is.null(d) == FALSE){
      if(d %in% common_questions){
        new_col[y] <- columns[x]
        y <- y + 1
      }
    }
    x <-  x + 1
  }
  new_col <- unlist(new_col)
  arg_test <- country[ ,new_col]
}

```

Need to try to make unique columns only, add to list and then make happen
```{r}
shrink2 <- function(country){
  y <- 1
  x <- 1
  new_col <- rep(NA, 128)
  columns <- attributes(country)$names
  while(x <= length(columns)){
    d <- (attributes(country[[columns[x]]]))$label
    if(is.null(d) == FALSE){
      if(d %in% common_questions){
        new_col[y] <- columns[x]
        y <- y + 1
      }
    }
    x <-  x + 1
  }
  new_col <- unlist(new_col)
  arg_test <- country[ ,new_col]
}

```



```{r}
argentina_shrinkx  <- shrink2(argentina)
belize_shrinkx  <- shrink2(belize)
bolivia_shrinkx  <- shrink2(bolivia)
brazil_shrinkx  <- shrink2(brazil)
canada_shrinkx  <- shrink2(canada)
chile_shrinkx <- shrink2(chile)
colombia_shrinkx  <- shrink2(colombia)
costa_shrinkx <- shrink2(costa)
ecuador_shrinkx <- shrink2(ecuador)
elsalvador_shrinkx <- shrink2(elsalvador)
guatemala_shrinkx <- shrink2(guatemala)
#guyana_shrinkx <- shrink2(guyana) Commented out because it is English-only
honduras_shrinkx <- shrink2(honduras)
#jamaica_shrinkx <- shrink2(jamaica) Commented out because it is English-only
mexico_shrinkx <- shrink2(mexico)
nicaragua_shrinkx <- shrink2(nicaragua)
panama_shrinkx <- shrink2(panama)
paraguay_shrinkx <- shrink2(paraguay)
peru_shrinkx <- shrink2(peru)
suriname_shrinkx <- shrink2(suriname)
usa_shrinkx <- shrink2(usa)
uruguay_shrinkx <- shrink2(uruguay)
venezuela_shrinkx <- shrink2(venezuela)
```
