---
title: "5-creating unique id and numbered column"
output: html_notebook
---

Makes a unique and common id format 

#PART A
```{r}
making_uniqueID <- function(country){
  #Combines idnum and idnum_14 with "/" and then makes unique id
  country <- mutate(country,
                    idnum = ifelse(idnum_14 == '',
                                   idnum,
                                   paste(idnum,idnum_14,sep = "/")))
  
  mutate(country,
         unique_id = paste(
           paste(
             toupper(substr(pais, 1, 3)),
             substr(year, 3, 4), sep = ''),
           idnum, sep = "_"))
}

extra_id <- function(country) {
  i <- 1
  #Object column is the length of idnum column
  column <- length(country$idnum)
  #Repeats NA for length column
  number_for_dupID <- rep(NA, column)
  #Loop that adds row number
  while(i <= column){
    number_for_dupID[i] <- i
    i <- i + 1
  }
  number_for_dupID
}

full_id <- function(country){
  country <- making_uniqueID(country)
  extra_id <- extra_id(country)
  #Makes extra column, numbered by row
  country <- country %>%
    mutate(extra_id)
  country
}
  
#countries <- list(argentina,belize, bolivia, brazil, canada, chile, colombia, costa, ecuador, elsalvador, guatemala, honduras, mexico, nicaragua, panama, peru, suriname, usa, uruguay, venezuela)
#Removed Guyan and Jamaica 6/27
  

```



```{r}
argentina_unique <- full_id(argentina_vb)
belize_unique <- full_id(belize_vb)
bolivia_unique <- full_id(bolivia_vb)
brazil_unique <- full_id(brazil_vb)
canada_unique <- full_id(canada_vb)
chile_unique <- full_id(chile_vb)
colombia_unique <- full_id(colombia_vb)
costa_unique <- full_id(costa_vb)
ecuador_unique <- full_id(ecuador_vb)
elsalvador_unique <- full_id(elsalvador_vb)
guatemala_unique <- full_id(guatemala_vb)
#guyana_unique <- full_id(guyana_vb)
honduras_unique <- full_id(honduras_vb)
#jamaica_unique <- full_id(jamaica_vb)
mexico_unique <- full_id(mexico_vb)
nicaragua_unique <- full_id(nicaragua_vb)
panama_unique <- full_id(panama_vb)
paraguay_unique <- full_id(paraguay_vb)
peru_unique <- full_id(peru_vb)
suriname_unique <- full_id(suriname_vb)
usa_unique <- full_id(usa_vb)
uruguay_unique <- full_id(uruguay_vb)
venezuela_unique <- full_id(venezuela_vb)
```


#PART B

```{r}
making_uniqueID <- function(country){
  #Combines idnum and idnum_14 with "/" and then makes unique id
  country <- mutate(country,
                    idnum = ifelse(idnum_14 == '',
                                   idnum,
                                   paste(idnum,idnum_14,sep = "/")))
  
  mutate(country,
         unique_id = paste(
           paste(
             toupper(substr(pais, 1, 3)),
             substr(year, 3, 4), sep = ''),
           idnum, sep = "_"))
}

extra_id <- function(country) {
  i <- 1
  #Object column is the length of idnum column
  column <- length(country$idnum)
  #Repeats NA for length column
  number_for_dupID <- rep(NA, column)
  #Loop that adds row number
  while(i <= column){
    number_for_dupID[i] <- i
    i <- i + 1
  }
  number_for_dupID
}

full_id <- function(country){
  country <- making_uniqueID(country)
  extra_id <- extra_id(country)
  #Makes extra column, numbered by row
  country <- country %>%
    mutate(extra_id)
  country
}
  
#countries <- list(argentina,belize, bolivia, brazil, canada, chile, colombia, costa, ecuador, elsalvador, guatemala, honduras, mexico, nicaragua, panama, peru, suriname, usa, uruguay, venezuela)
#Removed Guyan and Jamaica 6/27
  

```


```{r}
argentina_unique_unfactor <- full_id(argentina_vb_unfactor)
belize_unique_unfactor <- full_id(belize_vb_unfactor)
bolivia_unique_unfactor <- full_id(bolivia_vb_unfactor)
brazil_unique_unfactor <- full_id(brazil_vb_unfactor)
canada_unique_unfactor <- full_id(canada_vb_unfactor)
chile_unique_unfactor <- full_id(chile_vb_unfactor)
colombia_unique_unfactor <- full_id(colombia_vb_unfactor)
costa_unique_unfactor <- full_id(costa_vb_unfactor)
ecuador_unique_unfactor <- full_id(ecuador_vb_unfactor)
elsalvador_unique_unfactor <- full_id(elsalvador_vb_unfactor)
guatemala_unique_unfactor <- full_id(guatemala_vb_unfactor)
#guyana_unique_unfactor <- full_id(guyana_vb_unfactor)
honduras_unique_unfactor <- full_id(honduras_vb_unfactor)
#jamaica_unique_unfactor <- full_id(jamaica_vb_unfactor)
mexico_unique_unfactor <- full_id(mexico_vb_unfactor)
nicaragua_unique_unfactor <- full_id(nicaragua_vb_unfactor)
panama_unique_unfactor <- full_id(panama_vb_unfactor)
paraguay_unique_unfactor <- full_id(paraguay_vb_unfactor)
peru_unique_unfactor <- full_id(peru_vb_unfactor)
suriname_unique_unfactor <- full_id(suriname_vb_unfactor)
usa_unique_unfactor <- full_id(usa_vb_unfactor)
uruguay_unique_unfactor <- full_id(uruguay_vb_unfactor)
venezuela_unique_unfactor <- full_id(venezuela_vb_unfactor)
```

```{r}
making_uniqueID <- function(country){
  #Combines idnum and idnum_14 with "/" and then makes unique id
  country <- mutate(country,
                    `idnum-factor` = ifelse(`idnum_14-factor` == '',
                                   `idnum-factor`,
                                   paste(`idnum-factor`,`idnum_14-factor`, sep = "/")))
  
  mutate(country,
         unique_id = paste(
           paste(
             toupper(substr(`pais-factor`, 1, 3)),
             substr(`year-factor`, 3, 4), sep = ''),
           `idnum-factor`, sep = "_"))
}

extra_id <- function(country) {
  i <- 1
  #Object column is the length of idnum column
  column <- length(country$`idnum-factor`)
  #Repeats NA for length column
  number_for_dupID <- rep(NA, column)
  #Loop that adds row number
  while(i <= column){
    number_for_dupID[i] <- i
    i <- i + 1
  }
  number_for_dupID
}

full_id_factor <- function(country){
  country <- making_uniqueID(country)
  extra_id <- extra_id(country)
  #Makes extra column, numbered by row
  country <- country %>%
    mutate(extra_id)
  country
}
  
#countries <- list(argentina,belize, bolivia, brazil, canada, chile, colombia, costa, ecuador, elsalvador, guatemala, honduras, mexico, nicaragua, panama, peru, suriname, usa, uruguay, venezuela)
#Removed Guyan and Jamaica 6/27
  

```

```{r}
argentina_unique_factor <- full_id_factor(argentina_vb_factor)
belize_unique_factor <- full_id_factor(belize_vb_factor)
bolivia_unique_factor <- full_id_factor(bolivia_vb_factor)
brazil_unique_factor <- full_id_factor(brazil_vb_factor)
canada_unique_factor <- full_id_factor(canada_vb_factor)
chile_unique_factor <- full_id_factor(chile_vb_factor)
colombia_unique_factor <- full_id_factor(colombia_vb_factor)
costa_unique_factor <- full_id_factor(costa_vb_factor)
ecuador_unique_factor <- full_id_factor(ecuador_vb_factor)
elsalvador_unique_factor <- full_id_factor(elsalvador_vb_factor)
guatemala_unique_factor <- full_id_factor(guatemala_vb_factor)
#guyana_unique_factor <- full_id_factor(guyana_vb_factor)
honduras_unique_factor <- full_id_factor(honduras_vb_factor)
#jamaica_unique_factor <- full_id_factor(jamaica_vb_factor)
mexico_unique_factor <- full_id_factor(mexico_vb_factor)
nicaragua_unique_factor <- full_id_factor(nicaragua_vb_factor)
panama_unique_factor <- full_id_factor(panama_vb_factor)
paraguay_unique_factor <- full_id_factor(paraguay_vb_factor)
peru_unique_factor <- full_id_factor(peru_vb_factor)
suriname_unique_factor <- full_id_factor(suriname_vb_factor)
usa_unique_factor <- full_id_factor(usa_vb_factor)
uruguay_unique_factor <- full_id_factor(uruguay_vb_factor)
venezuela_unique_factor <- full_id_factor(venezuela_vb_factor)
```




