---
title: "6-tidying/gather and spread"
output: html_notebook
---

```{r}
library(tidyr)
library(tidyverse)
long_questions <- function(country, country_before, column){
			  #Starting at index 1
			  i <- 1
number_for_dupID <- rep(NA, column)
new_list <- rep(NA, column)
#Replaces original column names with readable version
			  while(i <= column){
			    #Isolates original column names
			    original <- (country$column_name)[i]
			    #Replaces with label
			    new <- attributes(country_before[[original]])$label
			    #Adds object to list
			    new_list[i] <- new
			    #Moves to next item
			    i <- i + 1
			  }
			  new_list
			}
lengthen <- function(country) {
			  country_before <- country
			  country <- country %>%
 #These are excluded because they are repeated
			  select(-strata,-sex, -vb11_10, -vb11_12) %>%
			  #Brings together the following columns
			  gather(column_name, answer, estratopri:vb_combined)
#Takes length of column_name and arguments from long_questions
			  column <- length(country$column_name)
			  questions <- long_questions(country, country_before, column)
 country <- country %>% 
			    mutate(questions)
country <- country %>% 
			    select(pais, year, unique_id, column_name, answer, questions, extra_id)
			  return(country)
			}

```


```{r}
tidy_spread <- function(x){
  x <- x %>%
    select(-column_name) %>%
    spread(questions, answer)
}
```


```{r}
belize_wide <- tidy_spread(lengthen(belize))
brazil_wide <- tidy_spread(lengthen(brazil))
chile_wide <- tidy_spread(lengthen(chile))
panama_wide <- tidy_spread(lengthen(panama))
paraguay_wide <- tidy_spread(lengthen(paraguay))
peru_wide <- tidy_spread(lengthen(peru))
suriname_wide <- tidy_spread(lengthen(suriname))
uruguay_wide <- tidy_spread(lengthen(uruguay))
venezuela_wide <- tidy_spread(lengthen(venezuela))
bolivia_wide <- tidy_spread(lengthen(bolivia))
canada_length <- lengthen(canada)
canada_wide <- tidy_spread(canada_length)
colombia_length <- lengthen(colombia)
colombia_wide <- tidy_spread(colombia_length)
costa_wide <- tidy_spread(lengthen(costa))
ecuador_wide <- tidy_spread(lengthen(ecuador))
elsalvador_wide <- tidy_spread(lengthen(elsalvador))
guatemala_wide <- tidy_spread(lengthen(guatemala))
honduras_wide <- tidy_spread(lengthen(honduras))
mexico_wide <- tidy_spread(lengthen(mexico))
nicaragua_wide <- tidy_spread(lengthen(nicaragua))
usa_wide <- tidy_spread(lengthen(usa))
```