---
title: "Adding Year Column"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Goal of the Document

The 2016 and 2017 files are missing a year column that is present in the merged files. The code below adds the correct year to the corresponding files.

## Lists of files by year

```{r}
countries_2016 <- list(colombia_16_factor, colombia_16_unfactor, costa_16_factor, costa_16_unfactor, elsalvador_16_factor, elsalvador_16_unfactor, guyana_16_factor, guyana_16_unfactor, honduras_16_factor, honduras_16_unfactor, nicaragua_16_factor, nicaragua_16_unfactor, paraguay_16_factor, paraguay_16_unfactor)
```

```{r}
countries_2017 <- list(argentina_16_factor, argentina_16_unfactor, bolivia_16_factor, bolivia_16_unfactor, brazil_16_factor, brazil_16_unfactor, canada_16_factor, canada_16_unfactor, chile_16_factor, chile_16_unfactor, guatemala_16_factor, guatemala_16_unfactor, jamaica_16_factor, jamaica_16_unfactor, mexico_16_factor, mexico_16_unfactor, peru_16_factor, peru_16_unfactor, usa_16_factor, usa_16_unfactor, uruguay_16_factor, uruguay_16_unfactor)
```

```{r}
countries_both <- list(ecuador_16_factor, ecuador_16_unfactor, venezuela_16_factor, venezuela_16_unfactor)
```



```{r}
add_wave_factor_2016 <- function(country){
  country <- country %>% mutate(`wave-factor` = 2016)
  return(country)
}
```

```{r}
add_wave_factor_2017 <- function(country){
  country <- country %>% mutate(`wave-factor` = 2017)
  return(country)
}
```

```{r}
add_wave_unfactor_2016 <- function(country){
  country <- country %>% mutate(wave = 2016)
  return(country)
}
```

```{r}
add_wave_unfactor_2017 <- function(country){
  country <- country %>% mutate(wave = 2017)
  return(country)
}

```

# 2016 datasets
```{r}
colombia_16_factor <- add_wave_factor_2016(colombia_16_factor)
colombia_16_unfactor <- add_wave_unfactor_2016(colombia_16_unfactor)
costa_16_factor <- add_wave_factor_2016(costa_16_factor)
costa_16_unfactor <- add_wave_unfactor_2016(colombia_16_unfactor)
ecuador_16_factor <- add_wave_factor_2016(ecuador_16_factor)
ecuador_16_unfactor <- add_wave_unfactor_2016(ecuador_16_unfactor)
elsalvador_16_factor <- add_wave_factor_2016(elsalvador_16_factor)
elsalvador_16_unfactor <- add_wave_unfactor_2016(elsalvador_16_unfactor)
guyana_16_factor <- add_wave_factor_2016(guyana_16_factor)
guyana_16_unfactor <- add_wave_unfactor_2016(guyana_16_unfactor)
honduras_16_factor <- add_wave_factor_2016(honduras_16_factor)
honduras_16_unfactor <- add_wave_unfactor_2016(honduras_16_unfactor)
nicaragua_16_factor <- add_wave_factor_2016(nicaragua_16_factor)
nicaragua_16_unfactor <- add_wave_unfactor_2016(nicaragua_16_unfactor) 
paraguay_16_factor <- add_wave_factor_2016(paraguay_16_factor)
paraguay_16_unfactor <- add_wave_unfactor_2016(paraguay_16_unfactor)

```

# 2017 datasets
```{r}
argentina_16_factor <- add_wave_factor_2017(argentina_16_factor)
argentina_16_unfactor <- add_wave_unfactor_2017(argentina_16_unfactor)
bolivia_16_factor <- add_wave_factor_2017(bolivia_16_factor)
bolivia_16_unfactor <- add_wave_unfactor_2017(bolivia_16_unfactor)
brazil_16_factor <- add_wave_factor_2017(brazil_16_factor)
brazil_16_unfactor <- add_wave_unfactor_2017(brazil_16_unfactor)
canada_16_factor <- add_wave_factor_2017(canada_16_factor)
canada_16_unfactor <- add_wave_unfactor_2017(canada_16_unfactor)
chile_16_factor <- add_wave_factor_2017(chile_16_factor)
chile_16_unfactor <- add_wave_unfactor_2017(chile_16_unfactor)
guatemala_16_factor  <- add_wave_factor_2017(guatemala_16_factor)
guatemala_16_unfactor <- add_wave_unfactor_2017(guatemala_16_unfactor) 
jamaica_16_factor  <- add_wave_factor_2017(jamaica_16_factor) 
jamaica_16_unfactor <- add_wave_unfactor_2017(jamaica_16_unfactor)
mexico_16_factor <- add_wave_factor_2017(mexico_16_factor)
mexico_16_unfactor <- add_wave_unfactor_2017(mexico_16_unfactor)
panama_16_factor <- add_wave_factor_2017(panama_16_factor)
panama_16_unfactor <- add_wave_unfactor_2017(panama_16_unfactor)
peru_16_factor <- add_wave_factor_2017(peru_16_factor)
peru_16_unfactor <- add_wave_unfactor_2017(peru_16_unfactor)
usa_16_factor <- add_wave_factor_2017(usa_16_factor)
usa_16_unfactor <- add_wave_unfactor_2017(usa_16_unfactor)
uruguay_16_factor <- add_wave_factor_2017(uruguay_16_factor) 
uruguay_16_unfactor <- add_wave_unfactor_2017(uruguay_16_unfactor)
```

# Assumed 2016 wave
```{r}
ecuador_16_factor <- add_wave_factor_2016(ecuador_16_factor) 
ecuador_16_unfactor <- add_wave_unfactor_2016(ecuador_16_unfactor)
```








