---
title: "Categories and Questions-factors"
output: html_notebook
---

```{r}
factored_category_names <- c("pais-factor",
             "factor-factor",
             "idnum-factor",
             "estratopri-factor",
             "upm-factor",
             "prov-factor",
             "municipio-factor",
             "cluster-factor",
             "ur-factor",
             "tamano-factor","q1-factor",
             "immig1-factor",
             "immig2-factor",
             "dis2-factor",
             "dis4-factor",
             "dis5-factor",
             "ednivel-factor",
             "edanno-factor",
             "ed-factor",
             "q2-factor",
             "q3-factor",
             "q5a-factor",
             "q10-factor",
             "q10a-factor",
             "q10a1-factor",
             "q10b-factor",
             "q10c-factor",
             "q16-factor",
             "q14-factor",
             "q10d-factor",
             "q11-factor",
             "q12-factor",
             "q12a-factor",
             "etid-factor",
             "leng1-factor",
             "www1-factor",
             "r1-factor",
             "r3-factor",
             "r4-factor",
             "r4a-factor",
             "r5-factor",
             "r6-factor",
             "r7-factor",
             "r8-factor",
             "r12-factor",
             "r14-factor",
             "r15-factor",
             "ocup4a-factor",
             "ocup1-factor",
             "ocup1a-factor",
             "ocup12a-factor",
             "ocup1c-factor",
             "ocup28-factor",
             "ocup29-factor",
             "ocup30-factor",
             "ocup31-factor",
             "ocup31a-factor",
             "mig1-factor",
             "mig2-factor",
             "mig3-factor","year-factor",
                "idiomaq-factor",
                "fecha-factor",
                "hora1-factor",
                "a4-factor",
                "l1-factor",
                "hora-factor",
                "hora-factor",
                "ti-factor",
	"soct1-factor",
	"soct2-factor",
	"idio1-factor",
	"idio2-factor",
	"ls3-factor",
	"ls6-factor",
	"ls4-factor",
	"cp2-factor",
	"cp4a-factor",
	"cp4-factor",
	"cp5-factor",
	"cp6-factor",
	"cp7-factor",
	"cp8-factor",
	"cp9-factor",
	"cp10-factor",
	"cp13-factor",
	"cp20-factor",
	"prot1-factor",
	"prot2-factor",
	'np1-factor',
	'np1b-factor',
	'np2-factor',
	'sgl1-factor',
	'sgl2-factor',
	'lgl2-factor',
	'lgl2a-factor',
	'lgl2b-factor',
	'lgl3-factor',
	'muni5-factor',
	'muni6-factor',
	'muni8-factor',
	'muni9-factor',
	'muni10-factor',
	'muni11-factor',
	'muni15-factor',
	'it1-factor',
	'it1a-factor',
	'it1b-factor',
	'vic1-factor',
	'aoj1-factor',
	'aoj1b-factor',
	'vic20-factor',
	'vic21-factor',
	'vic27-factor',
	'aoj8-factor',
	'aoj11-factor',
	'aoj11a-factor',
	'aoj12-factor',
	'aoj12a-factor',
	'aoj16a-factor',
	'aoj17-factor',
	'aoj18-factor',
	'st1-factor',
	'st2-factor',
	'st3-factor',
	'st4-factor',
  'b1-factor',
	'b2-factor',
  'b3-factor',
  'b4-factor',
  'b6-factor',
	'b10a-factor',
	'b11-factor',
	'b12-factor',
	'b13-factor',
	'b14-factor',
	'b15-factor',
	'b16-factor',
	'b18-factor',
	'b20-factor',
	'b21-factor',
	'b21a-factor',
	'b31-factor',
	'b32-factor',
	'b43-factor',
	'b17-factor',
	'b19-factor',
	'b33-factor',
	'b37-factor',
	'b42-factor',
	'b50-factor',
	'b47-factor',
	'b48-factor',
	'b23-factor',
	'b46-factor',
	'n1-factor',
	'n3-factor',
	'n9-factor',
	'n10-factor',
	'n11-factor',
	'n12-factor',
	'm1-factor',
	'm2-factor',
	'd32-factor',
	'd33-factor',
	'd34-factor',
	'd36-factor',
	'd37-factor',
	'd1-factor',
	'd2-factor',
	'd3-factor',
	'd4-factor',
	'd5-factor',
	'e5-factor',
	'e8-factor',
	'e11-factor',
	'e15-factor',
	'e14-factor',
	'e2-factor',
	'e3-factor',
	'e16-factor',
	'ing4-factor',
	'pn2-factor',
	'dem23-factor',
	'pn4-factor',
	'pn5-factor',
	'dem2-factor',
	'dem11-factor',
	'jc1-factor',
	'jc4-factor',
	'jc10-factor',
	'jc12-factor',
	'jc13-factor',
	'jc15-factor',
	'jc16-factor',
	'aut1-factor',
	'aut2-factor',
	'dc10-factor',
	'dc13-factor',
	'exc2-factor',
	'exc6-factor',
	'exc11a-factor',
	'exc13a-factor',
	'exc14a-factor',
	'exc15a-factor',
	'exc16a-factor',
	'exc11-factor',
	'exc13-factor',
	'exc14-factor',
	'exc15-factor',
	'exc16-factor',
	'exc17-factor',
	'exc18-factor',
	'exc7-factor',
	'pp1-factor',
	'pp2-factor',
	'vb1-factor',
	'vb2-factor',
	'vb3-factor',
	'vb50-factor',
	'vb10-factor',
	'vb11-factor',
	'vb12-factor',
	'vb20-factor',
	'vb21-factor',
	'a1-factor',
	'a2-factor',
	'a3-factor',
	'a4i-factor',
	'epp1-factor',
	'epp2-factor',
	'epp3-factor',
	'ec1-factor',
	'ec2-factor',
	'ec3-factor',
	'ec4-factor',
	'pop101-factor',
	'pop102-factor',
	'pop103-factor',
	'pop106-factor',
	'pop107-factor',
	'pop109-factor',
	'pop110-factor',
	'pop112-factor',
	'pop113-factor',
	'eff1-factor',
	'eff2-factor',
	'ros1-factor',
	'ros2-factor',
	'ros3-factor',
	'ros4-factor',
	'gi1-factor',
	'gi2-factor',
	'gi3-factor',
	'gi4-factor',
	'gi5-factor',
	'pol1-factor',
	'pol2-factor',
	'sd1-factor',
	'sd2-factor',
	'sd3-factor',
	'sd4-factor',
	'sd5-factor',
	'sd6-factor',
	'sd7-factor',
	'sd8-factor',
	'sd9-factor',
	'sd10-factor',
	'sd11-factor',
	'sd12-factor',
	'ocup12-factor',
	'ocup27-factor'
)
```


```{r}
cat_one_factor <- c("pais-factor",
             "factor-factor",
             "idnum-factor",
             "estratopri-factor",
             "upm-factor",
             "prov-factor",
             "municipio-factor",
             "cluster-factor",
             "ur-factor",
             "tamano-factor")
```

```{r}
cat_two_factor <- c("q1-factor",
             "immig1-factor",
             "immig2-factor",
             "dis2-factor",
             "dis4-factor",
             "dis5-factor",
             "ednivel-factor",
             "edanno-factor",
             "ed-factor",
             "q2-factor",
             "q3-factor",
             "q5a-factor",
             "q10-factor",
             "q10a-factor",
             "q10a1-factor",
             "q10b-factor",
             "q10c-factor",
             "q16-factor",
             "q14-factor",
             "q10d-factor",
             "q11-factor",
             "q12-factor",
             "q12a-factor",
             "etid-factor",
             "leng1-factor",
             "www1-factor",
             "r1-factor",
             "r3-factor",
             "r4-factor",
             "r4a-factor",
             "r5-factor",
             "r6-factor",
             "r7-factor",
             "r8-factor",
             "r12-factor",
             "r14-factor",
             "r15-factor",
             "ocup4a-factor",
             "ocup1-factor",
             "ocup1a-factor",
             "ocup12a-factor",
             "ocup1c-factor",
             "ocup28-factor",
             "ocup29-factor",
             "ocup30-factor",
             "ocup31-factor",
             "ocup31a-factor",
             "mig1-factor",
             "mig2-factor",
             "mig3-factor")
```

```{r}
cat_three_factor <- 	c("year-factor",
                "idiomaq-factor",
                "fecha-factor",
                "hora1-factor",
                "a4-factor",
                "l1-factor",
                "hora-factor",
                "hora-factor",
                "ti-factor")
```

```{r}
cat_four_factor <- c(
	"soct1-factor",
	"soct2-factor",
	"idio1-factor",
	"idio2-factor",
	"ls3-factor",
	"ls6-factor",
	"ls4-factor")
```

```{r}
cat_five_factor <- c(
	"cp2-factor",
	"cp4a-factor",
	"cp4-factor",
	"cp5-factor",
	"cp6-factor",
	"cp7-factor",
	"cp8-factor",
	"cp9-factor",
	"cp10-factor",
	"cp13-factor",
	"cp20-factor",
	"prot1-factor",
	"prot2-factor")
```

```{r}
cat_six_factor <- c(
	'np1-factor',
	'np1b-factor',
	'np2-factor',
	'sgl1-factor',
	'sgl2-factor',
	'lgl2-factor',
	'lgl2a-factor',
	'lgl2b-factor',
	'lgl3-factor',
	'muni5-factor',
	'muni6-factor',
	'muni8-factor',
	'muni9-factor',
	'muni10-factor',
	'muni11-factor',
	'muni15-factor')
```

```{r}
cat_seven_factor <- list(
	'it1-factor',
	'it1a-factor',
	'it1b-factor')
```

```{r}
cat_eight_factor <- list(
	'vic1-factor',
	'aoj1-factor',
	'aoj1b-factor',
	'vic20-factor',
	'vic21-factor',
	'vic27-factor',
	'aoj8-factor',
	'aoj11-factor',
	'aoj11a-factor',
	'aoj12-factor',
	'aoj12a-factor',
	'aoj16a-factor',
	'aoj17-factor',
	'aoj18-factor',
	'st1-factor',
	'st2-factor',
	'st3-factor',
	'st4-factor')
```

# !No values for category nine given
```{r}
cat_nine_factor <- list()
```


```{r}
cat_ten_factor <- list(
  'b1-factor',
	'b2-factor',
  'b3-factor',
  'b4-factor',
  'b6-factor',
	'b10a-factor',
	'b11-factor',
	'b12-factor',
	'b13-factor',
	'b14-factor',
	'b15-factor',
	'b16-factor',
	'b18-factor',
	'b20-factor',
	'b21-factor',
	'b21a-factor',
	'b31-factor',
	'b32-factor',
	'b43-factor',
	'b17-factor',
	'b19-factor',
	'b33-factor',
	'b37-factor',
	'b42-factor',
	'b50-factor',
	'b47-factor',
	'b48-factor',
	'b23-factor',
	'b46-factor',
	'n1-factor',
	'n3-factor',
	'n9-factor',
	'n10-factor',
	'n11-factor',
	'n12-factor',
	'm1-factor',
	'm2-factor')
```

```{r}
cat_eleven_factor <- c(
	'd32-factor',
	'd33-factor',
	'd34-factor',
	'd36-factor',
	'd37-factor',
	'd1-factor',
	'd2-factor',
	'd3-factor',
	'd4-factor',
	'd5-factor')
```

```{r}
cat_twelve_factor <- c(
	'e5-factor',
	'e8-factor',
	'e11-factor',
	'e15-factor',
	'e14-factor',
	'e2-factor',
	'e3-factor',
	'e16-factor')
```

```{r}
cat_thirteen_factor <- c(
	'ing4-factor',
	'pn2-factor',
	'dem23-factor',
	'pn4-factor',
	'pn5-factor',
	'dem2-factor',
	'dem11-factor')
```

```{r}
cat_fourteen_factor <- c(
	'jc1-factor',
	'jc4-factor',
	'jc10-factor',
	'jc12-factor',
	'jc13-factor',
	'jc15-factor',
	'jc16-factor',
	'aut1-factor',
	'aut2-factor')
```

```{r}
cat_fifteen_factor <- c(
	'dc10-factor',
	'dc13-factor',
	'exc2-factor',
	'exc6-factor',
	'exc11a-factor',
	'exc13a-factor',
	'exc14a-factor',
	'exc15a-factor',
	'exc16a-factor',
	'exc11-factor',
	'exc13-factor',
	'exc14-factor',
	'exc15-factor',
	'exc16-factor',
	'exc17-factor',
	'exc18-factor',
	'exc7-factor')
```

```{r}
cat_sixteen_factor <- c(
	'pp1-factor',
	'pp2-factor',
	'vb1-factor',
	'vb2-factor',
	'vb3-factor',
	'vb50-factor',
	'vb10-factor',
	'vb11-factor',
	'vb12-factor',
	'vb20-factor',
	'vb21-factor')
```

# !No values for category seventeen given
```{r}
cat_seventeen_factor <- c()
```

```{r}
cat_eighteen_factor <- c(
	'a1-factor',
	'a2-factor',
	'a3-factor',
	'a4i-factor',
	'epp1-factor',
	'epp2-factor',
	'epp3-factor',
	'ec1-factor',
	'ec2-factor',
	'ec3-factor',
	'ec4-factor',
	'pop101-factor',
	'pop102-factor',
	'pop103-factor',
	'pop106-factor',
	'pop107-factor',
	'pop109-factor',
	'pop110-factor',
	'pop112-factor',
	'pop113-factor',
	'eff1-factor',
	'eff2-factor',
	'ros1-factor',
	'ros2-factor',
	'ros3-factor',
	'ros4-factor',
	'gi1-factor',
	'gi2-factor',
	'gi3-factor',
	'gi4-factor',
	'gi5-factor',
	'pol1-factor',
	'pol2-factor',
	'sd1-factor',
	'sd2-factor',
	'sd3-factor',
	'sd4-factor',
	'sd5-factor',
	'sd6-factor',
	'sd7-factor',
	'sd8-factor',
	'sd9-factor',
	'sd10-factor',
	'sd11-factor',
	'sd12-factor',
	'ocup12-factor',
	'ocup27-factor'
)
```