---
title: "lengthen"
output: html_notebook
---

```{r}
long_questions <- function(country, country_before, column){
			  #Starting at index 1
			  i <- 1
number_for_dupID <- rep(NA, column)
new_list <- rep(NA, column)
#Replaces original column names with readable version
			  while(i <= column){
			    #Isolates original column names
			    original <- (country$column_name)[i]
			    #Replaces with label
			    new <- attributes(country_before[[original]])$label
			    #Adds object to list
			    new_list[i] <- new
			    #Moves to next item
			    i <- i + 1
			  }
			  new_list
			}
lengthen <- function(country) {
			  country_before <- country
			  country <- country %>%
 #These are excluded because they are repeated
			  select(-sex, -vb11_10, -vb11_12) %>%
			  #Brings together the following columns
			  gather(column_name, answer, estratopri:vb_combined)
#Takes length of column_name and arguments from long_questions
			  column <- length(country$column_name)
			  questions <- long_questions(country, country_before, column)
 country <- country %>% 
			    mutate(questions)
country <- country %>% 
			    select(pais, year, unique_id, column_name, answer, questions, extra_id)
			  return(country)
country <- country %>% mutate("common" = column_name %in% common_unfactor)
			}

```



```{r}
argentina_long_unfactor <- lengthen(argentina_unique_unfactor)
```

```{r}
long_questions(argentina_long_unfactor, argentina_unique_unfactor)
```


