---
title: "Testing Wide Unique ID"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Structure
I am testing to ensure that the person ID is unique. This affects the data later on.

```{r}
library(assertr)
library(purrr)
```


## Asserts
Going to check them individually
```{r}
#Successful
argentina_unique_unfactor %>% 
  assert(is_uniq, person_id)
#Successful
belize_unique_unfactor%>% 
  assert(is_uniq, person_id)
```

Making a function for it
```{r}
check_unique <- function(country) {
  country %>% 
    assert(is_uniq, person_id)
}
```

```{r}
unfactored_countries <- list(argentina_unique_unfactor, belize_unique_unfactor, bolivia_unique_unfactor, brazil_unique_unfactor, canada_unique_unfactor, chile_unique_unfactor, colombia_unique_unfactor, costa_unique_unfactor, ecuador_unique_unfactor, elsalvador_unique_unfactor, guatemala_unique_unfactor, guyana_unique_unfactor, honduras_unique_unfactor, jamaica_unique_unfactor, mexico_unique_unfactor, nicaragua_unique_unfactor, panama_unique_unfactor, paraguay_unique_unfactor, peru_unique_unfactor, suriname_unique_unfactor, usa_unique_unfactor, uruguay_unique_unfactor, venezuela_unique_unfactor)
```

```{r}
map(unfactored_countries, check_unique)
```

Okay so it says that an issue starts at 1004, but person_id violates the assertion is_uniq 377 times, so we've got to find that. Going to check individually again.

```{r}
#Failed - 377 times
check_unique(bolivia_unique_unfactor)
#Successful!
check_unique(brazil_unique_unfactor)
#Failed - 70 times
check_unique(canada_unique_unfactor)
#Successful!
check_unique(chile_unique_unfactor)
#Failed - 4 times
check_unique(colombia_unique_unfactor)
#Failed - 4496 times
check_unique(costa_unique_unfactor)
#Failed - 4 times
check_unique(ecuador_unique_unfactor)
#Failed - 96 times
check_unique(elsalvador_unique_unfactor)
#Failed - 8 times
check_unique(guatemala_unique_unfactor)
#Successful!
check_unique(guyana_unique_unfactor)
#Failed - 5 times
check_unique(honduras_unique_unfactor)
#Failed - 4 times
check_unique(jamaica_unique_unfactor)
#Failed - 1134 times
check_unique(mexico_unique_unfactor)
#Failed - 2 times
check_unique(nicaragua_unique_unfactor)
#Successful!
check_unique(panama_unique_unfactor)
#Successful!
check_unique(paraguay_unique_unfactor)
#Successful!
check_unique(peru_unique_unfactor)
#Successful!
check_unique(suriname_unique_unfactor)
#Successful!
check_unique(usa_unique_unfactor)
#Successful!
check_unique(uruguay_unique_unfactor)
#Successful!
check_unique(venezuela_unique_unfactor)
```

