---
title: "Combine"
output: html_notebook
---

```{r}
together <- function(unfactor,factor){
  unfactor <- unfactor %>% select(-pais, -year,-unique_id, -extra_id, -category)
  final <- bind_cols(factor,unfactor)
  return(final)
}
```




```{r}
panama <- together(panama_wide, panama_wide_factor)
argentina <- together(argnetina_wide, argentina_wide_factor)
bolivia <- bind_cols(bolivia_wide, bolivia_wide_factor)
brazil <- together(brazil_wide, brazil_wide_factor)
belize <- together(belize_wide, belize_wide_factor)
canada <- together(canada_wide, canada_wide_factor)
chile <- together(chile_wide, chile_wide_factor)
colombia <- together(colombia_wide, colombia_wide_factor)
costa <- together(costa_wide, costa_wide_factor)
ecuador <- together(ecuador_wide, ecuador_wide_factor)
elsalvador <- together(elsalvador_wide, elsalvador_wide_factor)
guatemala <- together(guatemala_wide, guatemala_wide_factor)
guyana <- together(guyana_wide, guyana_wide_factor)
paraguay <- together(paraguay_wide, paraguay_wide_factor)
honduras <- together(honduras_wide, honduras_wide_factor)
jamaica <- together(jamaica_wide, jamaica_wide_factor)
mexico <- together(mexico_wide, mexico_wide_factor)
nicaragua <- together(nicaragua_wide, nicaragua_wide_factor)
peru <- together(peru_wide, peru_wide_factor)
suriname <- together(suriname_wide, suriname_wide_factor)
usa <- together(usa_wide, usa_wide_factor)
uruguay <- together(uruguay_wide, uruguay_wide_factor)
venezuela <- together(venezuela_wide, venezuela_wide_factor)
```

```{r}
first <- bind_rows(argentina, bolivia)
second <- bind_rows(first, brazil)
third <- bind_rows(second, belize)
fourth <- bind_rows(third, canada)
fifth <- bind_rows(fourth, chile)
sixth <- bind_rows(fifth, colombia)
seven <- bind_rows(sixth, costa)
eigth <- bind_rows(seven, ecuador)
nine <- bind_rows(eigth, elsalvador)
ten <- bind_rows(nine, guatemala)
eleven <- bind_rows(ten, guyana)
twelve <- bind_rows(eleven, paraguay)
thirteen <- bind_rows(twelve, honduras)
fourteen <- bind_rows(thirteen, jamaica)
fifteen <- bind_rows(fourteen, mexico)
sixteen <- bind_rows(fifteen, nicaragua)
seventeen <- bind_rows(sixteen, panama)
eighteen <- bind_rows(seventeen, peru)
nineteen <- bind_rows(eighteen, suriname)
twenty <- bind_rows(nineteen, usa)
twen_one <- bind_rows(twenty, uruguay)
last_combine <- bind_rows(twen_one, venezuela)

write_csv(last_combine, "combined_tidy.csv")
```

